# Generated by Django 2.2 on 2020-11-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojosninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
